### ISSUE TITLE
Error in equation 2.55

### ISSUE THREAD

**Issue by cneyens** [pythongroundwaterbook/analytic_gw_book#2]
Equation 2.55 on page 40 contains an arithmetic error I believe. The `cosh` terms should be summed, not subtracted. In the corresponding python code, this is coded correctly.

**Comment by mbakker7** [comment]
Thank you for reporting this apparent discrepancy. We will look into it soon.

**Comment by mbakker7** [comment]
An erratum notebook with a correction has been added. Thanks for reporting this issue!
