### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by cneyens** [pythongroundwaterbook/analytic_gw_book#3]
Hello,

I finished the book. I found it to be a very educational read, certainly for someone as me with limited experience in analytical groundwater flow modelling. I believe I've found some errors in the equations/code cells. I do apologize if this comes across as pedantic, which is certainly not my intent.

1. Eq. 6.66: in the definition of $h_1$, the second term between the brackets should have a + sign instead of a - sign. This is coded correctly in the corresponding code cell.
2. Figure 6.15: to obtain this figure, the corresponding code cell should plot `-Q0tot / Q` and `-Q1tot / Q` (i.e. minus signs should be added). Additionally, the x-label on the right plot should read $r/\lambda$ instead of $r~(m)$.
3. p. 146: in the set-up of the head-specified line-sink model, the first definition of `xls` seems redundant?
4. p. 165: The minus sign in equation 9.48 is incorrect I believe. The definition of `Qrbar` in the code cell on the next page does not show this sign. Also, there is no code for the creation of the right plot panel of figure 9.8.
5. p. 187: in the code cell, `qtop` should be multiplied by 1000.

Kind regards,
Cas

**Comment by mbakker7** [comment]
Thanks for this excellent feedback, @cneyens !
Not pedantic at all. We tried our best to avoid any errors in the book. 
With the help of our readers we can also find the last ones. 
We'll take a look at it and post any necessary corrections soon.

**Comment by mbakker7** [comment]
All 5 corrections have been made. Thanks for reporting these errors. 
(When I used a pre-published version of this book to teach my groundwater modeling class, I promised students a Mars bar for every error they found. So if I ever run into you, and you like Mars bars, please let me know).

**Comment by cneyens** [comment]
Fantastic. I'll be at the MODFLOW & MORE congress next week in Princeton, so maybe I'll see you there!
